### PR TITLE
Problems with proxy

### PR DESCRIPTION
**Pull request by shelld3v**
Description
---------------

Bug fix with proxy

### CODE REVIEW

**Comment by maurosoria** [comment]
I don't think request by name should be mandatory (the same reason why --ip is still useful) when using proxies.

Sometimes you want to use a proxy but setting directly the hostname.

**Comment by shelld3v** [comment]
Have you ever tries to use the `--proxy` feature? I used Burp as a proxy and everything I saw in my dashboard is IP addresses. Use proxies, YOU CAN't SET THE HOST HEADER, and this will MAKE A LOT OF PROBLEMS (In most servers, if you don't set the host header to the correct hostname, you will unable to hit the website). I will say this is A SUPER IMPORTANT BUG FIX and don't know why it was there for years!

**Comment by shelld3v** [comment]
What a normal code do:

```python
requests.get('http://google.com', proxies={'http':'127.0.0.1:8080'})
```

But what you do:

```python
requests.get('http://172.217.161.174', proxies={'http':'127.0.0.1:8080'})
```

And this is not what the user expects.

**Comment by maurosoria** [comment]
Screen Shot 2020-11-11 at 14 42 35

I tested the feature, and it works as expected. As you see Burp you show the IP address in the table, but the HOST header is correct.

I don't know if you meant something else. Can you clarify?

**Comment by shelld3v** [comment]
Oh, I didn't check the host header, sorry for that. But I believe it is really really important to set `requestByHostname`, as in a normal use case

**Comment by shelld3v** [comment]
https://github.com/maurosoria/dirsearch/pull/556#issuecomment-723757637

**Pull request merged**
