### PR TITLE
camelCase to snake_case for some core files

### PR DESCRIPTION
**Pull request by jsfan**
Description
---------------

Some more PEP8 alignment with lowerCamelCase variables renamed to snake_case.

This is still part of #144

*Note:* While I have been very careful while renaming, there is a risk of some breakage here. The problem is that many of the renamed variables are copied from command line options which remain in lowerCamelCase.

### CODE REVIEW

**Comment by shelld3v** [comment]
Hi, have you taken a look at my PRs? This will generate a lot of conflicts

**Comment by shelld3v** [comment]
```
$ git clone https://github.com/jsfan/dirsearch.git
Cloning into 'dirsearch'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 5264 (delta 4), reused 6 (delta 4), pack-reused 5251
Receiving objects: 100% (5264/5264), 18.99 MiB | 1.72 MiB/s, done.
Resolving deltas: 100% (3346/3346), done.
$ cd dirsearch
$ python3 dirsearch.py -E -u example.com
Traceback (most recent call last):
  File "dirsearch.py", line 47, in <module>
    main = Program()
  File "dirsearch.py", line 36, in __init__
    self.arguments = ArgumentParser(self.script_path)
  File "/tmp/dirsearch/dirsearch/lib/core/argument_parser.py", line 70, in __init__
    if options.noExtension:
AttributeError: 'Values' object has no attribute 'noExtension'
$
```

**Comment by shelld3v** [comment]
Hi, is this really important? I am thinking that:

- 100% of our variables now are camelCase, edit all of them is super complex
- This isn't really useful in any possible way
- We have been too familar with camelCase variables and are creating those everyday, so I really don't like to change it to snake_case

I don't think we should do this, seriously!

**Comment by jsfan** [comment]
> ```
> $ git clone https://github.com/jsfan/dirsearch.git
> Cloning into 'dirsearch'...
> remote: Enumerating objects: 13, done.
> remote: Counting objects: 100% (13/13), done.
> remote: Compressing objects: 100% (9/9), done.
> remote: Total 5264 (delta 4), reused 6 (delta 4), pack-reused 5251
> Receiving objects: 100% (5264/5264), 18.99 MiB | 1.72 MiB/s, done.
> Resolving deltas: 100% (3346/3346), done.
> $ cd dirsearch
> $ python3 dirsearch.py -E -u example.com
> Traceback (most recent call last):
>   File "dirsearch.py", line 47, in <module>
>     main = Program()
>   File "dirsearch.py", line 36, in __init__
>     self.arguments = ArgumentParser(self.script_path)
>   File "/tmp/dirsearch/dirsearch/lib/core/argument_parser.py", line 70, in __init__
>     if options.noExtension:
> AttributeError: 'Values' object has no attribute 'noExtension'
> $
> ```

I seem to have been too careful there. I'll rename what is missing.

**Comment by jsfan** [comment]
> Hi, is this really important? I am thinking that:
> 
>     * 100% of our variables now are camelCase, edit all of them is super complex
> 
>     * This isn't really useful in any possible way
> 
>     * We have been too familiar with camelCase variables, and are creating those everyday, so I really don't like to change it to snake_case
> 
> 
> I don't think that we should do this, seriously! And I am seeing A LOT of python projects don't follow and don't care about `snake_case`, like sqlmap. Since creating a variable with a good and easy to read name is enough (`includeStatusCodes` is better than `include_status_codes` from my eyes)

I kept going because @maurosoria indicated that he would like the code to be compliant. Yes, there will be a little bit of work in the changeover (most of it mine though) but it will be successive and manageable.

The argument that plenty of projects are non-compliant doesn't make any sense to me. A standard is only as good as it is adopted and I could also write a lot of bad code on the premise that there is already plenty of bad code out there.

**Comment by jsfan** [comment]
I have now fixed misnomers which resulted in the script not starting at all. I'll go over the diff again soon but feel free to review as well.

**Comment by jsfan** [comment]
I just reviewed the diff again and fixed a couple more mistakes. It all looks good now.

I've also fixed a small bug and a help text which was hard to understand.

**Comment by jsfan** [comment]
@maurosoria I'll leave it at this until you have voiced an opinion as to if you would consider merging this or now. I know @shelld3v is a major contributor of functionality, so I understand if you side with him. I just want to avoid putting in too much effort before I know it's worth it.

**Comment by shelld3v** [comment]
The fact that I hate to work with `snake_case`, my eyes don't like them. Currently, I don't know why we should change this! Will it boost up the speed? Or improve the readability? If you are saying it will be easier to read `snake_case` variables, then it's just with you, not me. I love `camelCase`, this standard may good with you, but not with some others. And keeping the old standard won't impact anything.

**Comment by jsfan** [comment]
My argument remains the same. Adhering to a standard makes it easier for people who are used to working within the framework to quickly find their way around. The snake_case is just part of that. If you get a full-blood Python coder on the project (s)he will probably introduce snake_case just because that's what Python coders do.

I can say that personally, I'd be more likely to contribute to a project where I consider the code base clean than one that looks messy to me. At the moment, I'd put `dirsearch` in the latter category and the camelCase is part of that (even though not the most important part).

TBH, `dirsearch` probably needs unit tests more desperately than snake_case. Going through it for the PEP8 compliance, I have seen quite a bit of code which looked wrong to me. Sometimes, it was wrong because of how Python works, even though the code would look right to someone who isn't used to Python. Sometimes, it was probably just plain wrong logic which no test could ever pick up because there are none.

**Comment by shelld3v** [comment]
There is no framework here. This won't help anyone easier to work with, at least for me, and I am a contributor of this project! A variable name is like an art, it will be good with this person but not with another. And I think that variable names won't mess up everything or make the code wrong as what you said. You don't need to follow anything that everyone says it's right, everything depends on you! Of course if you and @maurosoria like it, I can do nothing. But I want to say it will hard for me to work with `snake_case`

**Comment by jsfan** [comment]
I disagree with the statement about conventions and standards not helping with wrapping your head around things. I have worked with quite a number of small and large codebases and the ones which had clear conventions and standards were much easier to get started on.

As for the wrong code, I was not suggesting that it is due to the camelCase. Of course, it is not. What I meant is that looking around the code base, it is rather messy and not too well structured. That's not surprising because it has grown over some time. However, conventions help with cleaning that up and keeping it clean and even things as small as variable name conventions help there. A clean code base (and even better one with test coverage) is much easier to reason about, maintain and extend. That includes consistent naming which in Python is snake_case because it is consistent across many packages. While there are packages that do not follow the convention, they tend to be small in number and often not in a great state because they were written by people with limited proficiency in Python.

**Comment by shelld3v** [comment]
>I disagree with the statement about conventions and standards not helping with wrapping your head around things. I have worked with quite a number of small and large codebases and the ones which had clear conventions and standards were much easier to get started on.

No, nothing in this world is working with EVERYONE. There are some people feel good with this, but some are not, including me!

**Comment by jsfan** [comment]
Again, I was not suggesting that there is a convention that is better than all others. I'm suggesting that a conventions as such is helpful. And, in Python camelCase means breaking with common convention across packages. I use camelCase when I write code in languages where that is the common convention, e.g. JavaScript, Go, PHP, Java, etc..

**Comment by shelld3v** [comment]
Of course, I am only saying what I WANT, not something that you MUST follow.

**Comment by shelld3v** [comment]
Hey @maurosoria, please don't merge this PR now! It will create a lot of conflicts with my period PRs, those are new features + bug fixes

**Comment by maurosoria** [comment]
@jsfan check your github email

**Pull request closed without merging**
