### PR TITLE
Added feature for former DirBuster Users

### PR DESCRIPTION
**Pull request by vlohacks**
Hi, 

Like your tool very much, thanks for the effort, it is a cool successor for the abandoned DirBuster tool. I missed one feature to use a plain dirbuster wordlist with extensions and added it, maybe you also find it useful. 
Added option -f / --force-extenisons to brute force a plain wordlist with all extensions (like in dirbuster) without needing the %EXT% wildcard.

Regards Florian

### CODE REVIEW

**Comment by maurosoria** [comment]
Welcome vlohacks, thanks for the contribution

I'll test the path and merge as soon as possible.

**Comment by maurosoria** [comment]
Please, remove this line from the commit

self.output.newLine("\n" + str(self.arguments.forceExtensions))

**Comment by vlohacks** [comment]
Hi,
Removed the line, sry for the late reply

**Comment by maurosoria** [comment]
Done! Great work!

**Pull request merged**
