### PR TITLE
Add, Sort and Remove Duplicate

### PR DESCRIPTION
**Pull request by drego85**
Description
---------------

- Add subdir "_borders" and "_themes" by default on websites created with FrontPage
- Remove duplicate entry
- Sort

### CODE REVIEW

**Comment by shelld3v** [comment]
Oh, mine was uppercase -> lowercase

**Comment by drego85** [comment]
I've removed duplicate lines with case sensitive:
- 71 duplicates case sensitive;
- 247 duplicates NO case sensitive.

**Comment by maurosoria** [comment]
Thanks @drego85 ?

How are you doing? sorry for being so late. Hope you are okay

Regards,
Mauro

**Comment by drego85** [comment]
Hi Mauro,
fortunately all right!

Thanks to you for the time you dedicate to this project!

**Pull request merged**
