### PR TITLE
Some initial PEP8 cleanup

### PR DESCRIPTION
**Pull request by jsfan**
This is just the low-hanging fruit. More to come.

Sending the PR now to make you aware.

This partially address #144.

### CODE REVIEW

**Comment by jsfan** [comment]
This still doesn't remove all warnings in `pycodestyle` or `flake8`. However, the question is if you want to follow PEP8 in all aspects. Many projects disagree e.g. with the line length limit and disable that warning.

**Comment by jsfan** [comment]
Once all warnings are gone or ignored, it would make sense to set up a Travis pipeline to enforce them for future patches. That would then also allow for adding some unit testing later.

**Comment by maurosoria** [comment]
@jsfan @shelld3v 


Can we do this now?

**Comment by shelld3v** [comment]
No, the code has changed so much, so we can't know if this pull request can create any problem. We can use this as an example of how to cleanup pep8 someday. I will do something like this in the future, safely, but not now. I think we can close this, thank you @jsfan, we appreciate your help and will use this as a doc in further updating!!!

**Comment by jsfan** [comment]
If I find the time, I'll go through the code as it is now and redo the cleanup.

**Comment by shelld3v** [comment]
Thank you ❤️

**Pull request closed without merging**
