### PR TITLE
Allow any HTTP method rather than just GET, POST, HEAD (and fixed some stuff)

### PR DESCRIPTION
**Pull request by shelld3v**

### CODE REVIEW

**Comment by maurosoria** [comment]
Hello @shelld3v 

The PR has a dangerous eval function. I cannot accept this PR, I am sorry.

Regards,
Mauro

**Review by maurosoria — CHANGES_REQUESTED** [review]
look for method self.session.request(self.httpmethod, url, **kwargs)
requests.request(method, url, **kwargs)[source]
https://requests.readthedocs.io/en/latest/api/

**Comment by shelld3v** [comment]
Edited! Is that correct?

**Comment by shelld3v** [comment]
>The PR has a dangerous eval function

We have already checked the HTTP method in **Controller.py** if it is valid or not so I don't think it's dangerous

**Pull request merged**
