### PR TITLE
set_target before we parse the URL and then use self.url

### PR DESCRIPTION
**Pull request by nrathaus**
# Description

What will it do?

If this PR will fix an issue, please address it:
https://github.com/maurosoria/dirsearch/issues/1357

# Recreate issue

Without the fix run:
`dirsearch "--url=scanme.nmap.org"`

Report will be generated at:
`/reports/_scanme.nmap.org/__24-04-30_15-05-07.txt`

With fix run and the report will be stored at:
`/reports/http_scanme.nmap.org/__24-04-30_15-05-07.txt`

### CODE REVIEW

**Comment by shelld3v** [comment]
Won't this make us run `set_target` twice? One in `run()` and one in `setup_reports()`?

**Comment by nrathaus** [comment]
I didn't observe this - are you seeing this happening?

**Comment by shelld3v** [comment]
Luckily, running `set_target` twice doesn't cause any significant impact here, but it still makes us waste some HTTP requests, as well as a weird-looking code, therefore we still have to change it. What's your idea of fixing, @nrathaus?

**Comment by shelld3v** [comment]
Also this won't fix the bug you mentioned in the description, if you give it a list of URLs. For example, a file containing targets like this:
```
https://example.com
scanme.nmap.org
```
It will still give us `_scanme.nmap.org` instead of `http_scanme.nmap.org`.

**Comment by shelld3v** [comment]
@maurosoria Hi can you revert this PR real quick? It doesn't really address the issue and actually causes more issues

**Comment by nrathaus** [comment]
The idea of the fix was to pass to `set_target` the scheme, as set_target created the file/folders

**Pull request merged**
