### PR TITLE
Fix `setup.py` / `pip install .`

### LINKED ISSUE #736: Python overwrites some PyPi packages when installing dirsearch with setup.py
I'm having this error when I run it with a non root user, I've tried doing it with `sudo` as well but I had the same error prompt
dirsearcherror
[dirsearchError.txt](https://github.com/maurosoria/dirsearch/files/5838254/dirsearchError.txt)

```
  File "/opt/dirsearch/dirsearch.py", line 47, in <module>
    main = Program()
  File "/opt/dirsearch/dirsearch.py", line 43, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/opt/dirsearch/lib/controller/controller.py", line 170, in __init__
    self.setupErrorLogs()
  File "/opt/dirsearch/lib/controller/controller.py", line 337, in setupErrorLogs
    self.errorLog = open(self.errorLogPath, "w")
PermissionError: [Errno 13] Permission denied: '/opt/dirsearch/logs/errors-21-01-19_13-39-11.log'
```
I tried to review the error log but doesn't exist.

### PR DESCRIPTION
**Pull request by qumusabel**
Fix #736

Initial version of the fix, plain `python setup.py install` still produces the bug, however `pip install .` seems to install `dirsearch` cleanly now.

Logs are still put into `site-packages/dirsearch/...` by default.

### CODE REVIEW

**Comment by maurosoria** [comment]
Hello @qumusabel !! Thanks for contributing!


Let's wait @shelld3v for approval, because he was the one following the issue.

Regards,
Mauro

**Comment by qumusabel** [comment]
Just noticed a comment I forgot to remove.

**Comment by shelld3v** [comment]
Hey there @qumusabel, is there any way to include `db/` folder?

**Review by shelld3v — APPROVED** [review]
Thank you!

**Comment by shelld3v** [comment]
@qumusabel I saw that you forgot to add your name to `CONTRIBUTORS.md`. Can you submit a pull request for it?

**Comment by qumusabel** [comment]
> Hey there @qumusabel, is there any way to include db/ folder?

Yes
```diff
     package_data={
-        "dirsearch": ["*"]
+        "dirsearch": ["*", "db/*"]
     },
```

**Comment by shelld3v** [comment]
> > Hey there @qumusabel, is there any way to include db/ folder?
> 
> Yes
> 
> ```diff
>      package_data={
> -        "dirsearch": ["*"]
> +        "dirsearch": ["*", "db/*"]
>      },
> ```

Can you submit a PR for it?

**Pull request merged**
