### PR TITLE
Swapped to Jinja2 for the HTML template

### PR DESCRIPTION
**Pull request by shelld3v**
Description
---------------

Swapped to Jinja2 for the HTML template

### CODE REVIEW

**Comment by shelld3v** [comment]
@wdahlenburg Can you resolve conflicts and apply these changes?

```patch
diff --git a/lib/reports/html_report.py b/lib/reports/html_report.py
index cc81bdc..2f4f020 100644
--- a/lib/reports/html_report.py
+++ b/lib/reports/html_report.py
@@ -66,7 +66,7 @@ class HTMLReport(FileBaseReport):
                     "redirect": e.response.redirect
                 })

-        return template.render(metadata=metadata, results=json.dumps(results))
+        return template.render(metadata=metadata, results=results)

     def save(self):
         self.file.seek(0)
diff --git a/lib/reports/templates/html_report_template.html b/lib/reports/templates/html_report_template.html
index 68cd0f3..76faf85 100644
--- a/lib/reports/templates/html_report_template.html
+++ b/lib/reports/templates/html_report_template.html
@@ -23,7 +23,7 @@ window.onload = function () {
       data() {
         return {
             searchQuery: null,
-            resources: {{ results }}
+            resources: {{ results | tojson }}
         };
       },
       computed: {
```

**Comment by wdahlenburg** [comment]
@shelld3v I tested the command string, URL, content-type, and redirect fields for XSS and SSTI. Let me know if you see any discrepancies.

**Comment by shelld3v** [comment]
I really want to merge your PR rn but I can't because I'm the PR submitter, can't approve the PR

**Comment by wdahlenburg** [comment]
> I really want to merge your PR rn but I can't because I'm the PR submitter, can't approve the PR

Do you want to close the PR and I can resubmit it, so that you can review it?

**Comment by shelld3v** [comment]
Sounds good

**Comment by shelld3v** [comment]
I did submit the PR for you because I thought that I could resolve conflicts and do some changes directly to the branch, but that wasn't the case

**Comment by wdahlenburg** [comment]
@shelld3v no worries. See #918

**Pull request closed without merging**
