### PR TITLE
Fixed dirsearch from adding dirs to queue when recursive arg is not specified

### PR DESCRIPTION
**Pull request by Knowledge-Wisdom-Understanding**
Description
---------------
Fixed dirsearch from adding dirs to queue when recursive arg is not specified

Why this PR? What will it do?
This PR will prevent dirsearch from adding found directories to the queue when the recursive argument is not specified.

If this PR will fix an issue, please address it:
Fix #{issue} I don't think there is an open issue for this yet, the fix was only 1 line that needed to be updated.
I can create an issue for this if need be.

Currently, in the master branch, I've noticed that dirsearch was adding a bunch of found dirs to the queue even though the -r
 --recursive option was not specified on the command line which can make dirsearch take forever on a non-recursive crawl.

### CODE REVIEW

**Comment by shelld3v** [comment]
Hi, I think dirsearch is working normally and your PR will create the problem like what you said. If `self.recursive is True`, means the user has used the recursive argument, then dirsearch will add found dirs to the Queue. In your code update, you set to `self.recursive is False`, which means if the user doesn't set the `--recursive` flag, dirsearch will add found dirs to the Queue!

**Comment by shelld3v** [comment]
Hey, actually you are right, you removed the `not`, not added it. Sorry!

**Comment by shelld3v** [comment]
And hey, there is a bug opened for this: #664

**Comment by maurosoria** [comment]
Hello @Knowledge-Wisdom-Understanding and @shelld3v 

First, thanks to @Knowledge-Wisdom-Understanding for contributing for first time! Welcome!

I see a conflict with this PR, can anybody of you fix it ? I don't want to screw it up.

Regards,
Mauro

**Comment by shelld3v** [comment]
@maurosoria You can fix this by your self, just by removing the `not`.

**Comment by shelld3v** [comment]
And you have the permission to edit the PR, @maurosoria! Can you resolve it?

**Comment by shelld3v** [comment]
Or you can check out this PR: #667

**Comment by Knowledge-Wisdom-Understanding** [comment]
didn't realize @shelld3v had changes to controller.py merged into master 3 days ago. Accidentally resolved this conflict with older controller.py code so i think this PR is messed up now 😅 . My apologies. 
Kinda humorous for such a simple fix, gotta love merge conflicts 😩 
closing this PR and PR #667 should work fine. @maurosoria 
Happy Holidays ⛄

**Pull request closed without merging**
