### PR TITLE
PEP8 Compliance

### PR DESCRIPTION
**Pull request by jsfan**
Fixes all PEP8 violations except for line length and wildcard imports.

### CODE REVIEW

**Comment by shelld3v** [comment]
Hi @jsfan, I really love your work, it's awesome! But a little bit sorry because I just submitted some pull requests, and there will be several problems if we just continue. You should tell me before editing anything in the code and I will stop updating dirsearch. Sorry but it looks like you need to re-edit the code after @maurosoria merged my PRs (open). As an apology, you can invite me to your fork so I can edit with you!

**Comment by shelld3v** [comment]
Also, I saw that you are replacing double new-lines with a single new-line, I think it's not important and may make the code harder to read (with me), right?

**Comment by christian-detexian** [comment]
> Hi @jsfan, I really love your work, it's awesome! But a little bit sorry because I just submitted some pull requests, and there will be several problems if we just continue. You should tell me before editing anything in the code and I will stop updating dirsearch. Sorry but it looks like you need to re-edit the code after @maurosoria merged my PRs (open). As an apology, you can invite me to your fork so I can edit with you!

Happy to add you to my fork but I'm also happy to resolve conflicts. Worst case I go with your code and do the PEP8 cleanup again.

**Comment by christian-detexian** [comment]
> Also, I saw that you are replacing double new-lines with a single new-line, I think it's not important and may make the code harder to read (with me), right?

I'm following PEP8 which contains blank line rules. There is supposed to be one line at least except for the before classes and standalone functions where there have to be two.

To me, most of the extra blank lines looked quite random. If you want to indicate blocks, I'd suggest using comment lines instead.

Having said that, it's your code base. If you want me to ignore the blank line rule, I can do that. At the moment, my would be based on the output of

    flake8 --ignore=E501 .

which ignores only the 80-character line rule.

**Comment by shelld3v** [comment]
Thank you @christian-detexian! I will search more for pep8!

**Comment by shelld3v** [comment]
Hey, have you checked [this](http://pep8online.com/)?

**Comment by jsfan** [comment]
@shelld3v Sorry, if I caused confusion by posting from the wrong account above.

I have not tried the compliance checker you linked to above. However, you can get all the checking locally with `flake8` and `pycodestyle` as well.

**Comment by shelld3v** [comment]
No problem! I know that is you :)

**Comment by shelld3v** [comment]
There is a problem with this update: https://github.com/maurosoria/dirsearch/pull/446/commits/bff91f7f0a437ec1e21421102d0c9b015e6158a4#diff-8e1922148ef7ad4a87eb1d8667fad94d

**Comment by jsfan** [comment]
> There is a problem with this update: [bff91f7#diff-8e1922148ef7ad4a87eb1d8667fad94d](https://github.com/maurosoria/dirsearch/commit/bff91f7f0a437ec1e21421102d0c9b015e6158a4#diff-8e1922148ef7ad4a87eb1d8667fad94d)

What's the problem. The code  was broken. `suff` is only set in the loop but used in the condition for the loop. If you ever were to pass the first condition when `suff` is `None`, the second condition would throw a `TypeError`.

Now, the second condition is fulfilled if `suff` is `None`, allowing the loop to run to populate `suff`.

**Comment by jsfan** [comment]
I think I'll leave it at this. The wildcard imports are too much work even though I think you should really get rid of them.

I've also added Github Actions to run `flake8` over every commit. If you want to use them and maybe even gate your PRs with that check, you just have to switch on Actions.

**Comment by shelld3v** [comment]
Sorry, it's my fault! I supposed to be:

```python
        # Adding suffixes for finding backups etc
        if self._suffixes:
            for res in list(dict.fromkeys(result)):
                for suff in self._suffixes:
                    if not res.rstrip().endswith("/") and not res.rstrip().endswith(suff):
                        custom.append(res + suff)
```

Please change that!

**Comment by jsfan** [comment]
> Sorry, it's my fault! It supposed to be:
> 
> ```python
>         # Adding suffixes for finding backups etc
>         if self._suffixes:
>             for res in list(dict.fromkeys(result)):
>                 for suff in self._suffixes:
>                     if not res.rstrip().endswith("/") and not res.rstrip().endswith(suff):
>                         custom.append(res + suff)
> ```
> 
> Please change that!

That makes a lot more sense!

**Comment by shelld3v** [comment]
💯

**Comment by shelld3v** [comment]
Have you thought about your PR won't be applied because of my other PRs and you will need to do everything again?

**Comment by jsfan** [comment]
> Have you thought about your PR won't be applied because of my other PRs and you will need to do everything again?

Not a problem. Just get your PRs in and I'll resolve the conflicts.

**Comment by shelld3v** [comment]
👍 👍 👍 👍 👍 👍 👍 👍 👍

**Comment by shelld3v** [comment]
@jsfan whenever you can resolve all the conflicts, we will merge this PR

**Comment by jsfan** [comment]
I've resolved the conflicts, but the new code on `master` has introduced a long list of new violations which I will not be able to fix right now. So, you can merge, anyway, but the new checks will fail until the code has been cleaned up again.

**Comment by shelld3v** [comment]
There are several lines like `>>>>>>>>>>>>> master`, ... What are those lines?

**Comment by jsfan** [comment]
I must have missed something then. Let me fix.

**Comment by jsfan** [comment]
Sorry, I had rushed that. The missed conflict also caused most of the PEP8 violations. I have now fixed the conflicts and all new violations. This build should pass and be ready to merge.

**Comment by shelld3v** [comment]
Confirmed from my machine:

```bash
$ git clone https://github.com/jsfan/dirsearch.git -b pep8
Cloning into 'dirsearch'...
remote: Enumerating objects: 185, done.
remote: Counting objects: 100% (185/185), done.
remote: Compressing objects: 100% (152/152), done.
remote: Total 4204 (delta 106), reused 67 (delta 33), pack-reused 4019
Receiving objects: 100% (4204/4204), 18.62 MiB | 1.11 MiB/s, done.
Resolving deltas: 100% (2614/2614), done.
$ cd dirsearch
$ python3 dirsearch.py -E -u example.com -r -R 4 -X db,mdb,sql,shtml -C

  _|. _ _  _  _  _ _|_    v0.4.0
 (_||| _) (/_(_|| (_| )

Extensions: php, asp, aspx, jsp, jspx, html, htm, js | HTTP method: GET | Threads: 20 | Wordlist size: 10133 | Recursion level: 4

Error Log: /tmp/dirsearch/dirsearch/logs/errors-20-10-05_16-32-33.log

Target: example.com

Output File: /tmp/dirsearch/dirsearch/reports/example.com/_20-10-05_16-32-33.txt

[16:32:33] Starting:
[16:32:40] 403 -  345B  - /.dep.inc
[16:32:41] 403 -  345B  - /.env~
[16:32:44] 403 -  345B  - /.inc
[16:32:47] 403 -  345B  - /.travis.yml~
CTRL+C detected: Pausing threads, please wait...
[e]xit / [c]ontinue: c
CTRL+C detected: Pausing threads, please wait...
[e]xit / [c]ontinue: e

Canceled by the user
````
```

**Review by shelld3v — APPROVED** [review]
Confirmed from my side

**Comment by jsfan** [comment]
The conflict resolution was largely a no brainer. So, I'd be surprised if anything had broken. But, feel free to scrutinise the merge.

**Comment by jsfan** [comment]
@maurosoria Once you have merged this PR, you may want to mark `master` protected and only allow PRs which have passed the CI to be merged. That way, you can maintain PEP8 compliance as far as it has been achieved now.

**Comment by shelld3v** [comment]
Just forgot, I have submitted 6 more PRs

**Comment by jsfan** [comment]
@shelld3v I'm pretty sure, it will be easy to apply them on top of this one. Just run `flake8 . --exclude=thirdparty --count --ignore=E501,F403,F405` over your branches and fix whatever it spits out. If you have no PEP8 violations, you should not have any conflicts with my branch.

Alternatively, you can just merge my branch into each one of yours.

**Comment by maurosoria** [comment]
Hello guys!

First, I'd like to excuse myself for being so late.

I check the PR, it's great, but there is a problem: the thirdparty must not be modifed (for obvious reasons). That's why I haven't merged it yet. Can we sort this out?

Regards,
Mauro

**Comment by jsfan** [comment]
> I check the PR, it's great, but there is a problem: the thirdparty must not be modifed (for obvious reasons). That's why I haven't merged it yet. Can we sort this out?

@maurosoria I'm sorry about those modifications to the third party libraries. I made a few changes via regular expressions and must have failed to exclude `thirdparty` at some point. It should all be good now.

I've also merged `master` back into my branch and resolved all new conflicts.

**Comment by jsfan** [comment]
@shelld3v If this PR is going to sit here for a while without being merged, would you mind running `flake8 . --ignore=E501,F403,F405 --exclude=thirdparty` over your PRs and fix up the issues that come up, so I have less conflicts to resolve.

@maurosoria Given that this PR makes no functional changes, would you mind merging it with priority? I realise you are only merging bug fixes right now but if you leave this for too long, the work will have been for nothing once again.

**Comment by shelld3v** [comment]
@jsfan Thank you, I will stop everything now (except bug fix).

>@maurosoria Given that this PR makes no functional changes, would you mind merging it with priority? I realise you are only merging bug fixes right now but if you leave this for too long, the work will have been for nothing once again.

Yeah, he should merge this now!!!

**Comment by shelld3v** [comment]
@jsfan In my newest PRs, I have already do pep8 cleaning, the conflicts just happened because of the new code

**Comment by shelld3v** [comment]
@jsfan Please solve the final conflict

**Comment by jsfan** [comment]
Done :heavy_check_mark:

**Comment by shelld3v** [comment]
Fix #144

**Comment by shelld3v** [comment]
Hey @jsfan, I saw that in the file PrintOutput.py, you removed the `header()` function. Please don't, it will cause a bug if the user uses the --quite-mode. Can you re-add it?

**Comment by shelld3v** [comment]
Ohhh, actually there are 2 same functions, so you removed one 😝 But can you replace `self, s` with `self, text` 🌚???

**Comment by jsfan** [comment]
> Ohhh, actually there are 2 same functions, so you removed one stuck_out_tongue_closed_eyes But can you replace `self, s` with `self, text` new_moon_with_face???

I don't understand why because the method does nothing, anyway, but if you prefer `text` over `s`, I'll change it.

**Comment by shelld3v** [comment]
>if this PR keeps getting deprioritised.

No, this won't be. @maurosoria just usually get busy, I have seen something like this many times. He is really busy and he also afraid that PRs can add problems to his project, so he looks at everything very carefully before merging it.

**Comment by jsfan** [comment]
:+1:

**Pull request merged**
