### PR TITLE
Snake case + bug fixes

### PR DESCRIPTION
**Pull request by maxime-peim**
All is in the name, as asked in an issue, snake case is fixed in this PR. :)

### CODE REVIEW

**Comment by maxime-peim** [comment]
A re-read some, and it may fail for some variable defined in thirdparty/ since I did not have changed variable names in this directory.

**Comment by maurosoria** [comment]
Welcome @maxime-peim ! Thanks for spending your time in helping this project!

I quickly checked the PR and it looks great! I would take a short time to recheck it but I will mege it ASAP.

Regards,
Mauro

**Comment by maxime-peim** [comment]
Hi @maurosoria !
I am very glad to help, this is a reaaly helpful tool in CTF :)

**Comment by shelld3v** [comment]
Is that @jsfan🤣

**Comment by jsfan** [comment]
@shelld3v Not this time. I've run out of different Github accounts to use. :P

**Comment by maxime-peim** [comment]
I am sorry to have created a duplicate. Since the point is explicitly asked in #672 and that I want to become familiar with the code, I was thinking that would be a great first contribution :P

**Comment by shelld3v** [comment]
> I am sorry to have created a duplicate. Since the point is explicitly asked in #672 and that I want to become familiar with the code, I was thinking that would be a great first contribution :P

I appreciate that

**Comment by jsfan** [comment]
@maxime-peim I don't think it's a duplicate. I did part of this a while ago but haven't had a chance to finish it. So, thanks for taking it on. :)

**Review by shelld3v — APPROVED** [review]

**Comment by shelld3v** [comment]
@maxime-peim Sorry because some changes were merged into your branch, those are updates that I want to do, but afraid that I might create some conflicts with your PR

**Comment by maxime-peim** [comment]
Don't worry, if you want I can solve possible conflicts :)

**Comment by shelld3v** [comment]
Hey @maxime-peim, is there any way I can contact you (twitter or something)?

**Comment by maxime-peim** [comment]
Hi @shelld3v, you can contact me on discord at Maxou_#9933 !

**Comment by maxime-peim** [comment]
For sure, the Hack The Box one : [HTB server](https://discord.gg/hackthebox)

**Comment by shelld3v** [comment]
Hey @maxime-peim, I am having problem when trying to DM you, can you try if you can DM me?

**Comment by shelld3v** [comment]
@maxime-peim You can ping me in a channel, then click on that name and there will be several options including DM and send a friend request

**Comment by maxime-peim** [comment]
Do you use shelld3v as username ? Because I cannot found anybody called that way

**Comment by shelld3v** [comment]
Yeah, shelld3v

**Pull request merged**
