### PR TITLE
Release dirsearch v0.4.2

### PR DESCRIPTION
**Pull request by shelld3v**
Description
---------------

Release dirsearch v0.4.2 🎉

### CODE REVIEW

**Comment by shelld3v** [comment]
>Is mandatory to check the new dependencies (HttpNtlmAuth make use of some not builtin libraries). Best way is creating a virtualenv or a fresh box and test if everything works without the requirements.

I tested it, and it worked

>Testing HTML report and new report system (specially about mako templates, I don't know the security concerns or best practices)

I will, hope no SSTI will be found

>I guess we should wait for v0.4.3 for signatures and templates ...

What about v0.4.5 or v0.5.0? Want to raise it faster for v1.0.0

**Comment by shelld3v** [comment]
What about now?

**Comment by maurosoria** [comment]
@shelld3v !

I guess we should stop adding functionality. I'm concerned about the text "decoding" to Iso-8859-1. I speculate issues with that.

If do you agree, stop adding functionality until the 1st of June. If everything goes right, we release v.0.4.2 that day. Do you agree?

**Comment by shelld3v** [comment]
> @shelld3v !
> 
> I guess we should stop adding functionality. I'm concerned about the text "decoding" to Iso-8859-1. I speculate issues with that.
> 
> If do you agree, stop adding functionality until the 1st of June. If everything goes right, we release v.0.4.2 that day. Do you agree?

No problem

**Comment by shelld3v** [comment]
Ping

**Comment by shelld3v** [comment]
Bruh where is the release?

**Pull request merged**
