### PR TITLE
Snake case

### LINKED ISSUE #144: Need help for PEP8
Hi community!

I don't have much time lately, and I'd like to start applying this convention. So, I'm opening this issue looking for people who have time to do it.

If anyone is there, and you have experience with this convention, I'd really appreciate your help.

https://www.python.org/dev/peps/pep-0008/

I started writing this tool many years ago and I was used to write using lowerCamelCase Convention (hadn't written enough python code yet and didn't know so many people would use this tool really...) but know that I see that this piece of code might have some future, I think that using a convention it's necessary for the community driven development.

Anyone there?

### PR DESCRIPTION
**Pull request by jsfan**
Following on from #446 this PR transforms some camelCased names to snake_case.

This does **not** close #144 because there are many more occurrences of camelCase which should really be snake_case.

### CODE REVIEW

**Comment by jsfan** [comment]
it probably makes no sense to clean up all variable and method names in one PR because that would lead to a very large patch which would be impossible to review.

@shelld3v Does this look good to you so far? Feel free to modify in my repo again.

**Comment by shelld3v** [comment]
Why? I don't understand why you do this, most of variables I created when updating dirsearch are something like camelCased

**Comment by jsfan** [comment]
https://www.python.org/dev/peps/pep-0008/#id45

**Comment by jsfan** [comment]
It's not something `flake8` checks but it is part of PEP8.

**Comment by shelld3v** [comment]
I still don't think it's a good idea

**Comment by jsfan** [comment]
You don't have to go with it. The whole point of PEP8 though is that there are shared guidelines. So, if you were to find a contributor who is used to Python guidelines, they'd likely use snake case just as a Java coder would likely use camel case. Right now, the code base has not fixed style and my conclusion would be to go with what is generally adopted in the language it is written in. But, once again, it's your code base, so I'm only making a suggestion.

**Review by maurosoria — APPROVED** [review]

**Comment by jsfan** [comment]
@maurosoria I've resolved the conflicts.

**Comment by shelld3v** [comment]
I actually don't like this PR, but I'm not the owner

**Comment by maurosoria** [comment]
Hello @shelld3v and @jsfan 

I wanted to do this changes by myself, but I never have the opportunity (because it has to be done progressively). What @jsfan is pointing out is totally reasonably: if this is not done, PEP8 makes no sense.

Thanks @jsfan and @shelld3v !

**Pull request merged**
