### PR TITLE
Headers from file

### PR DESCRIPTION
**Pull request by chowmean**
Description
---------------

Why this PR? What will it do?

Adding Option to provide a feature where headers can be read from the file directly. 

If this PR will fix an issue, please address it:

Fix https://github.com/maurosoria/dirsearch/issues/292

### CODE REVIEW

**Comment by chowmean** [comment]
@shelld3v Please have a look.

**Review by shelld3v — CHANGES_REQUESTED** [review]
Hi, there are several things you need to solve:

- The help message is too long. Good message: "HTTP request headers list file", argument should be only `--headers-list`
- Your parser is not good at all. Please look at `urlList` or `proxyList` as an example. Try `File(headersFromFile) as headers`, `.exists()`, `.is_valid()`, ... Those are our built functions

Thank you for your help!!!

**Comment by chowmean** [comment]
@shelld3v Made the changes please have a look. My bad for not checking out the inbuilt functions.

**Review by shelld3v — APPROVED** [review]
🙏 🙏 🙏 

I just tested your patch in my machine and everything works perfectly. Thanks!

**Comment by shelld3v** [comment]
Hi, if you have free time, I hope you can update our README

**Comment by chowmean** [comment]
I have already updated the readme. Are there extra things need to be changed please let me know?

**Comment by shelld3v** [comment]
No, I mean if you can add more information about dirsearch features, how to use dirsearch smarty, ... Not the information about this update

**Comment by chowmean** [comment]
> No, I mean if you can add more information about dirsearch features, how to use dirsearch smarty, ... Not the information about this update

Sure I will have a look at this :) Do you have any slack channels or anything? Or should I create a PR regarding README and start adding things there.

**Comment by shelld3v** [comment]
A PR :) We are trying to create the best documentation ever for this awesome tool !!!

**Comment by shelld3v** [comment]
Hi, sorry, but can you update the CHANGELOG.md so the `Multiple bugfixes` will be at the last. Thank you!

**Comment by shelld3v** [comment]
Also, `--header-list` is much more correct than `--headers-list`. And if you don't mind, can you replace `headersFromFile` with `headerList`, so it will be the same as `urlList` and `proxyList`, the codebase will look better!

**Comment by shelld3v** [comment]
`HTTP request headers list file` => `File contains HTTP request headers`

🤣 🤣 🤣

**Comment by chowmean** [comment]
@shelld3v I hope this time it is fine. Most of the issues are with proper language and names. Done properly they increase the quality of the project.

**Comment by shelld3v** [comment]
👍

**Review by shelld3v — APPROVED** [review]

**Comment by shelld3v** [comment]
Hi, sorry again but can you add a space after the `,` in `line.split(":")[0].strip(),line.split(":")[1].strip()`? Dirsearch codebase is following pep8 for sure: #446

**Comment by maurosoria** [comment]
Hello @chowmean, thanks for contributing!

I haven't checked the feature, but apparently the order of the headers won't be as it would in the file, because you are not using an Ordered Set or an Ordered Dict. Am I right?

Regards,
Mauro

**Comment by shelld3v** [comment]
@maurosoria I don't think it is important at all

**Comment by maurosoria** [comment]
> @maurosoria I don't think it is important at all

yes it is, anyway we can still use this code:
https://github.com/maurosoria/robologin-dev/blob/master/lib/model/connection/HttpSession.py

**Comment by shelld3v** [comment]
I don't see the point!

**Comment by maurosoria** [comment]
The point is WAF check the order of the headers to detect BOTs. That's why is relevant.

**Comment by shelld3v** [comment]
I haven't seen anything like that!

**Pull request merged**
