### PR TITLE
Fix #1144

### LINKED ISSUE #1144: `NoneType` object is not iterable
### What is the current behavior?

There is a `TypeError`.

What actually happens?

It doesn't run. It exits because of the error.

### What is the expected behavior?
To not exit and show the usage message instead.

OS, python version, screenshots, dirsearch command, console output, ...?
```python
~# dirsearch 
Traceback (most recent call last):
  File "/usr/bin/dirsearch", line 68, in <module>
    main()
  File "/usr/bin/dirsearch", line 53, in main
    options = options()
  File "/scripts/dirsearch/lib/core/options.py", line 49, in options
    opt.urls = uniq(opt.urls)
  File "/scripts/dirsearch/lib/utils/common.py", line 33, in uniq
    return type_(filter(None, dict.fromkeys(array)))
TypeError: 'NoneType' object is not iterable
~# 
```
#### Checker:
 - [x] I tested in the latest version of dirsearch

### PR DESCRIPTION
**Pull request by shelld3v**

### CODE REVIEW

**Review by its0x08 — COMMENTED** [review]
I did pull the last changes, but still the same error.
I'm using **Python 3.10** btw and maybe your version of python runs it without errors.

**Comment by shelld3v** [comment]
@its0x08 What was your command, I thought you just ran `./dirsearch.py --raw-file file.txt`

**Comment by shelld3v** [comment]
Hello @its0x08, thanks for your early test of the fix, I have fixed it and I appreciate it. You might like to reach out to me via [discord](https://discord.gg/2N22ZdAJRj) so you can help us more in the future by testing

**Comment by its0x08** [comment]
Hello @shelld3v,

I simply typed `python dirsearch.py` and got the #1444 error message.


I joined your Slack, but there's no activity.
Probably because you moved to discord.
☺️

**Comment by shelld3v** [comment]
@its0x08 I got this:

```
$ python3 dirsearch.py
URL target is missing, try using -u <url>
```

**Comment by shelld3v** [comment]
@its0x08 Yes we moved to discord, please join

**Comment by its0x08** [comment]
> @its0x08 I got this:
> 
> ```
> $ python3 dirsearch.py
> URL target is missing, try using -u <url>
> ```

Now I got the same.
Thank you for the quick fix.

**Pull request merged**
