### PR TITLE
Update dicc.txt

### PR DESCRIPTION
**Pull request by atomiczsec**
Description
---------------

What will it do?
Add another directory
If this PR will fix an issue, please address it:
Fix #{issue}

Requirements
---------------

- [ ] Add your name to `CONTRIBUTERS.md`
- [ ] If this is a new feature, then please add some additional information about it to `CHANGELOG.md`

### CODE REVIEW

**Comment by shelld3v** [comment]
Hi, thank you for your contribution but I think there is one already
image

**Comment by atomiczsec** [comment]
I found a directory when it was by itself not with the second this before it

**Comment by shelld3v** [comment]
Can you add your name to CONTRIBUTERS.md?

**Comment by atomiczsec** [comment]
Sure, how would I do this? Sorry I am kind of new to using githubs features haha!

**Review by shelld3v — APPROVED** [review]

**Pull request merged**
