### PR TITLE
New feature: URLs from stdin

### PR DESCRIPTION
**Pull request by shelld3v**
Description
---------------

URLs from stdin. Example command:

```bash
$ amass enum -d yahoo.com -o yahoo.txt && cat yahoo.txt | httprobe -prefer-https | python3 dirsearch.py --stdin
```

### CODE REVIEW

**Comment by maurosoria** [comment]
Hello @shelld3v, how you doing?

First, I recommend to use splitlines instead of split("\n"), or directly use FileUtils getLines with stdin.

I have another question, did you do proper testing with large files?

**Comment by shelld3v** [comment]
Hi, `sys.stdin.read()` will give you a string object, there isn't the attribute `readlines()`.

>I have another question, did you do proper testing with large files

Yes

**Comment by maurosoria** [comment]
It's not readlines, is splitlines

Check the main function https://github.com/maurosoria/bugbounty-tools/blob/master/resolvedomains/resolvedomains.py

You can do it with FileUtils and sys.stdin

**Comment by maurosoria** [comment]
Another thing, most of tools use the '-' character to refer to the stdin. For example:
```
cat urls.txt | dirsearch -l - 
or
cat wordlist.txt | dirsearch -u target.com -w -
```

The stdin argument seems fine, but if you want to make it more fancy, the - syntax it's more familiar.

Just a suggestion, all solutions seem find to me.

**Comment by shelld3v** [comment]
> Another thing, most of tools use the '-' character to refer to the stdin. For example:
> 
> ```
> cat urls.txt | dirsearch -l - 
> or
> cat wordlist.txt | dirsearch -u target.com -w -
> ```
> 
> The stdin argument seems fine, but if you want to make it more fancy, the - syntax it's more familiar.
> 
> Just a suggestion, all solutions seem find to me.

Let's see



> Another thing, most of tools use the '-' character to refer to the stdin. For example:
> 
> ```
> cat urls.txt | dirsearch -l - 
> or
> cat wordlist.txt | dirsearch -u target.com -w -
> ```
> 
> The stdin argument seems fine, but if you want to make it more fancy, the - syntax it's more familiar.
> 
> Just a suggestion, all solutions seem find to me.

Nice, I will check it!

**Comment by shelld3v** [comment]
After thinking again, I decided not to make the `-` syntax as a signal to read URLs from stdin. Because it will be hard to notify people about that syntax (not everyone likes reading the README). And actually, not most of the tools use the '-' character to refer to the stdin, it was just an idea from GoBuster, then FFUF copied it (FFUF was inspired by GoBuster and wfuzz), feroxbuster is an example of not using that syntax.

Separate the `--stdin` flag will make things work easier!

**Comment by maurosoria** [comment]
Hello @shelld3v !

I merged the PR. The - syntax is not a gobuster idea (didn't know gobuster works that way), it's a convention for plenty of unix tools. 

https://unix.stackexchange.com/questions/16357/usage-of-dash-in-place-of-a-filename

**Comment by shelld3v** [comment]
Well, I will soon look again at this!

**Pull request merged**
