### PR TITLE
updated

### PR DESCRIPTION
**Pull request by gauravdrago**
Description
---------------

Why this PR? What will it do?

If this PR will fix an issue, please address it:
Fix #{issue}

Don't forget :)
---------------

 * Add your name to `CONTRIBUTERS.md`
 * If this is a new feature, then please add some additional information about it to `CHANGELOG.md`

Thank you very much for helping dirsearch become a better tool!!! :heart:

### CODE REVIEW

**Comment by shelld3v** [comment]
Hi, why did you remove `getfiles.php?f=http://xxx&t=js` and `admin/portalcollect.php?f=http://xxx&t=js`?

**Comment by gauravdrago** [comment]
> Hi, why did you remove `getfiles.php?f=http://xxx&t=js` and `admin/portalcollect.php?f=http://xxx&t=js`?

because it require to add custom host for response

**Comment by shelld3v** [comment]
Thanks for explaining!

**Review by shelld3v — APPROVED** [review]

**Review by shelld3v — CHANGES_REQUESTED** [review]
There is a conflict

**Review by knowthetech — COMMENTED** [review]
updates

**Pull request closed without merging**
