### PR TITLE
Shitty pep8

### PR DESCRIPTION
**Pull request by shelld3v**
Description
---------------

### CODE REVIEW

**Comment by jsfan** [comment]
If you think it's bad that PEP8 doesn'tlet you have unused variables, never try writing Go. Go won't compile if you have unused variables. ;)

**Comment by shelld3v** [comment]
I know that because I used to learn Golang. I mean that shit rule in Go, it's horrible right?

**Comment by jsfan** [comment]
I love it. I can't stand code bases full of cruft. I've spent a lot of time in my career figuring out code only to find out later that it wasn't actually used. Not allowing unused variables is a good start.

**Comment by shelld3v** [comment]
Not allowing unused variables is good, but it shouldn't be that hard!

**Comment by jsfan** [comment]
In theory, a warning would be enough. In practice, there are a lot of coders out there who ignore warnings altogether...

**Pull request merged**
