### PR TITLE
Clean code + reduce startup delay

### PR DESCRIPTION
**Pull request by shelld3v**
Description
---------------

This will allow us to skip the second test request if the first response gives us 404!

### CODE REVIEW

**Comment by shelld3v** [comment]
Hi, any problem with this? I can adjust if you want!!

**Comment by maurosoria** [comment]
Hello @shelld3v, I'm back. Hope you missed me 👍 

Can you add the same logic for the redirect regex, but for Set-Cookies too ? I always wondered what might happend.

**Comment by shelld3v** [comment]
>Can you add the same logic for the redirect regex, but for Set-Cookies too ? I always wondered what might happend.

Added into TODO 👍 

>Hello @shelld3v, I'm back. Hope you missed me 👍

100 percent

**Comment by shelld3v** [comment]
Think again, I may don't check the Set-Cookies header, because in some web apps, the Set-Cookies may be changed after each request!

**Pull request merged**
