### PR TITLE
Add @dipakpanchal456 as a contributor

### PR DESCRIPTION
**Pull request by shelld3v**
Description
---------------

Add @dipakpanchal456 as a contributor

### CODE REVIEW

**Review by dipakpanchal456 — CHANGES_REQUESTED** [review]
Can you edit this?
Dipak Panchal (th3.d1p4k)

**Comment by shelld3v** [comment]
Sure, change the name only?

**Comment by dipakpanchal456** [comment]
yes,
Dipak Panchal (th3.d1p4k <https://instagram.com/th3.d1p4k>)

**Comment by dipakpanchal456** [comment]
https://github.com/maurosoria/dirsearch/blob/master/CONTRIBUTORS.md

not updated yet

**Comment by shelld3v** [comment]
It needs to be merged by @maurosoria, please wait a couple of days (maybe tomorrow, who knows)

**Comment by shelld3v** [comment]
#848

**Comment by dipakpanchal456** [comment]
ok thank you

**Pull request closed without merging**
