### PR TITLE
[New Feature] --nmap-report 

### PR DESCRIPTION
**Pull request by archidote**
Description
---------------

Automate the detection of HTTP(S) services from a parsed nmap.xml report, eliminating the need for manual parsing. Ensure the inclusion of the **-sV** option during nmap scanning for comprehensive results.

*Here are two nmap commands I used when I developed this feature.*

```
nmap -p- -sV -oA nmap -iL IPs.txt
nmap -p- -sV -oA nmap 192.168.130.0/24
``` 

## Demo : 

https://github.com/maurosoria/dirsearch/assets/38756128/70116f22-1de7-49aa-af9a-275e86a6a304

Requirements
---------------

- [x] Add your name to `CONTRIBUTERS.md`
- [x] If this is a new feature, then please add some additional information about it to `CHANGELOG.md`

### CODE REVIEW

**Comment by shelld3v** [comment]
Hi @archidote, thanks a lot for your effort, but I'm wondering why did you decide to parse the nmap report and save it to another temporary file first before reading it, instead of just returning the URLs while reading the nmap report?

**Comment by archidote** [comment]
> Hi @archidote, thanks a lot for your effort, but I'm wondering why did you decide to parse the nmap report and save it to another temporary file first before reading it, instead of just returning the URLs while reading the nmap report?

Hi @shelld3v, 

Thanks for your comments, 

I must admit that this is the solution that seemed simplest to me when I devised this feature. 

But after rereading the code a second time, I realize that I could have used 

opt.urls = read_stdin().splitlines(0)

So I'm going to modify the code, it'll be cleaner you're right.

**Comment by archidote** [comment]
> > Hi @archidote, thanks a lot for your effort, but I'm wondering why did you decide to parse the nmap report and save it to another temporary file first before reading it, instead of just returning the URLs while reading the nmap report? 

Hi @shelld3v ! I've updated the code and the demo video.

**Comment by shelld3v** [comment]
Hi @archidote, there are a lot of problems with the code, but don't worry I have re-coded stuff locally, just currently I don't have nmap to test. If you want to help you can give me a heads up via Discord or whatever, otherwise I will continue this PR when I've done dealing with nmap installation 😀

**Comment by Prady18** [comment]
Thank you @archidote

**Review by shelld3v — APPROVED** [review]

**Comment by maurosoria** [comment]
Amazing commit! Thanks you very much!

Hope to see more PR in the future!


Thanks again 👍

**Pull request merged**
