### PR TITLE
Handle 429 Status Codes

### PR DESCRIPTION
**Pull request by wdahlenburg**
Description
---------------

429 Status Codes indicate the rate limit was exceeded. #504 was created as the initial solution of handling this. I added a few helper functions and resolved the deadlock. 

Moving the PR from (https://github.com/shelld3v/dirsearch/pull/2) to here. 

The jist of this is to allow the threads to be paused once a 429 is received. The user can decide to continue, exit, or skip the host. If the user continues, execution resumes and they are acknowledging that 429 status codes have been received, which will not be returned in the output after that point.

### CODE REVIEW

**Comment by shelld3v** [comment]
We will need to check this before merging!

**Comment by shelld3v** [comment]
And @wdahlenburg, you need to add this feature information to `CHANGELOG.md`

**Comment by shelld3v** [comment]
Or we can add this after releasing dirsearch v0.4.1 if you want @maurosoria

**Comment by maurosoria** [comment]
Thanks to @wdahlenburg for helping @shelld3v ! 

Love the fact that two people worked together for this particular feature =)

**Pull request merged**
