### PR TITLE
Adding the new WordPress SiteMaps filename

### PR DESCRIPTION
**Pull request by drego85**
More info:
* https://wordpress.org/support/topic/wordpress-5-5-adds-user-enumeration-to-wp-sitemap-xdel/
* https://make.wordpress.org/core/2020/07/22/new-xml-sitemaps-functionality-in-wordpress-5-5/

Description
---------------

What will it do?

If this PR will fix an issue, please address it:
Fix #{issue}

Requirements
---------------

- [ ] Add your name to `CONTRIBUTERS.md`
- [ ] If this is a new feature, then please add some additional information about it to `CHANGELOG.md`

### CODE REVIEW

**Comment by shelld3v** [comment]
Hi, why did you replace `!.gitignore` with `"!.gitignore`?

**Comment by drego85** [comment]
wow, good question! it was probably a typo :(

**Comment by drego85** [comment]
Ok, fixed!

**Review by shelld3v — APPROVED** [review]
Very nice!

**Pull request merged**
