### PR TITLE
Separate the 429 detection to an argument

### LINKED ISSUE #663: [e]xit / [c]ontinue / [i]gnore / [s]kip target:
:( :( :(

How avoid this ?!

### LINKED ISSUE #739: Is it possible to exit the dirsearch on 429 response code automatically
Hi Guys,
Is it possible to exit the dirsearch automatically when it encounter 429 response code. for example like `exit-on-429 ` option
```
[00:20:30] Starting: 
[00:21:32] 403 -   21B  - /%0a%0a<script>alert(\"Vulnerable\")</script>.jsp
429 status code detected: Pausing threads, please wait...
[e]xit / [c]ontinue / [i]gnore: e

Canceled by the user
```

Thank you.

### PR DESCRIPTION
**Pull request by shelld3v**
Description
---------------

Fix #739, fix #663

### CODE REVIEW

**Comment by bootyhunt3r** [comment]
Thank you so much for this fast update ! You guys are truly awesome !!!

**Comment by kotireddyaluri** [comment]
Thank you @shelld3v @maurosoria

**Comment by bootyhunt3r** [comment]
Thank you so much for this quick fix guys , @shelld3v @maurosoria , you guys arentruly awesome !

**Comment by shelld3v** [comment]
You don't need to say thanks, this is our mission. I will appreciate you guys if you can give us some feedback, special are feature suggestions, any feature that you think it's useful.

**Pull request merged**
