### PR TITLE
New feature: Exclude extensions (close #268)

### LINKED ISSUE #268: [Suggestion] Adding "exclude extensions" option
`dirsearch` should add a new option called "exclude extensions". This allows the user to select the extensions that he doesn't want to brute force with. For example, while hacking on Yahoo, I found that some of Yahoo servers didn't allow access to  `.jsp` files. Even the file existed or not (`blahthisdoesnotexist.jsp`), the server will always return a 403 error. So the "exclude extensions" option will not send any request which is `.jsp` extension, reduce spam outputs. The workflow is simple: remove all endpoints in the list that end with `.jsp`, then continue by brute-forcing with that endpoints list. 

Also, I want to develop dirsearch, can I join the dirsearch's developers team and help dirsearch grows the functionalities in directory brute-forcing? I will very careful when doing that, by testing with my fork first, then let you take a look at the update and apply if it's accepted by you.

Thank you for your attention

### PR DESCRIPTION
**Pull request by shelld3v**

### CODE REVIEW

**Comment by shelld3v** [comment]
Dude, plz do something good with the issues! Please set the labels, read all of them, ... If you are going to ignore all the issues, then at least set labels into it so I will work with them. Also please check out my issues, there are some stuff I want to ask or suggest you

**Comment by maurosoria** [comment]
Hello @shelld3v,

I look for the PRs in my free time. Also the same as the last ticket, a set does no preserve the order that user wants.

It's not olny a matter of performance

**Comment by shelld3v** [comment]
>Also the same as the last ticket, a set does no preserve the order that user wants.

I am using `oset` in my code 🤦

**Comment by shelld3v** [comment]
Also, can you recheck #275

**Pull request closed without merging**
