### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by shelld3v**

### CODE REVIEW

**Comment by maurosoria** [comment]
Hello!

I see some incorrect default headers. Also, remember most browsers use headers with an uppercase at the beginning.

**Comment by shelld3v** [comment]
@maurosoria dirsearch uses `CaseInsensitiveDict` for storing headers so it doesn't matter anyway. Plus HTTP headers are [officially] case-insensitive according to [RFC 2616](http://www.w3.org/Protocols/rfc2616/rfc2616.html), I haven't seen any web framework or any server that behaves differently with capitalized headers

**Comment by maurosoria** [comment]
Mmm please split the PR, the title says minor changes (but you modified 12 files)

**Comment by shelld3v** [comment]
It's called minor changes because I only changed the design/structure, didn't impact user experience. Maybe I should rename it to "Major changes"?:)

**Pull request closed without merging**
