### PR TITLE
New feature: Matches proxy

### PR DESCRIPTION
**Pull request by shelld3v**
Description
---------------

Replay requests for found paths with a specified proxy (like `-replay-proxy` in ffuf)

### CODE REVIEW

**Comment by maurosoria** [comment]
Hello @shelld3v, how you doing?

I have a question, what happened when if you have proxies and you want to replay only the matched request against that proxy?

**Comment by shelld3v** [comment]
Sorry if I don't understand your question, but this PR is made for that feature

**Comment by shelld3v** [comment]
`--proxy google.com:80 --matches-proxy facebook.com:80`. Google is the main proxy and Facebook is only be played with found paths

**Comment by shelld3v** [comment]
>Hello @shelld3v, how you doing?

I'm fine, thank you!!

**Pull request merged**
