### PR TITLE
Bug fix

### LINKED ISSUE #415: Getting configparser syntax error
Just pulled the latest update and now am unable to execute the program, getting the following error:

```shell
cfx:  /opt/dirsearch  |master ✓|
→ ./dirsearch.py
Traceback (most recent call last):
  File "./dirsearch.py", line 46, in <module>
    main = Program()
  File "./dirsearch.py", line 35, in __init__
    self.arguments = ArgumentParser(self.script_path)
  File "/opt/dirsearch/lib/core/ArgumentParser.py", line 30, in __init__
    self.parseConfig()
  File "/opt/dirsearch/lib/core/ArgumentParser.py", line 328, in parseConfig
    self.excludeSubdirs = config.safe_get("general", "exclude-subdirs", None)
  File "/opt/dirsearch/lib/utils/DefaultConfigParser.py", line 28, in safe_get
    result = configparser.ConfigParser.get(self, section, option)
  File "/usr/lib/python3.8/configparser.py", line 799, in get
    return self._interpolation.before_get(self, section, option, value,
  File "/usr/lib/python3.8/configparser.py", line 395, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.8/configparser.py", line 442, in _interpolate_some
    raise InterpolationSyntaxError(
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%ff/'
```

### PR DESCRIPTION
**Pull request by shelld3v**
Fix #415

### CODE REVIEW

**Comment by ColdFusionX** [comment]
This fixes the bug, but now we have to use a additional argument `-r` as we get the following usage displayed `--exclude-subdir argument can only be used with -r|--recursive` 

```shell
cfx:  /opt/dirsearch  |master U:1 ✗|
→ ./dirsearch.py -u http://target -w /usr/share/wordlists/seclists/Discovery/Web-Content/common.txt -E
--exclude-subdir argument can only be used with -r|--recursive
```

**Comment by tibug** [comment]
image
What is proplem

**Comment by shelld3v** [comment]
@ColdFusionX You say right!!

**Comment by shelld3v** [comment]
@ColdFusionX What do you think about my patch now?

**Comment by ColdFusionX** [comment]
@shelld3v Works flawlessly ! Thanks for your help.

**Pull request merged**
