### PR TITLE
Fixed dirsearch from adding dirs to queue when recursive arg is not specified (conflicts resolved)

### LINKED ISSUE #664: Recursive switch doesn't seem to work
recursive mode is not working for me

### PR DESCRIPTION
**Pull request by shelld3v**
Description
---------------

The same as #665 but conflicts resolved.

Fix #664

### CODE REVIEW

**Review by Knowledge-Wisdom-Understanding — APPROVED** [review]
Looks good, Thanks! @shelld3v

**Comment by shelld3v** [comment]
Thank you

**Comment by shelld3v** [comment]
I thought you don't want to fix conflicts, and the bug impacts a lot to dirsearch users, so created another one :)

**Comment by shelld3v** [comment]
And also, applying this PR will add your name to README, CONTRIBUTERS.md but won't add your name to the [Contributors metrics](https://github.com/maurosoria/dirsearch/graphs/contributors), which is really unfair at some points (with other contributors)! Can you try if you can submit any other PR? ;)

**Comment by Knowledge-Wisdom-Understanding** [comment]
> And also, applying this PR will add your name to README, CONTRIBUTERS.md but won't add your name to the [Contributors metrics](https://github.com/maurosoria/dirsearch/graphs/contributors), which is really unfair at some points (with other contributors)! Can you try if you can submit any other PR? ;)

Sure, I will submit another PR, hopefully there aren't any conflicts this time lol. @shelld3v

**Comment by shelld3v** [comment]
Thanks

**Pull request closed without merging**
