### PR TITLE
Check the scheme of the URL

### PR DESCRIPTION
**Pull request by shelld3v**
Description
---------------

Full check the protocol

### CODE REVIEW

**Comment by maurosoria** [comment]
Hello @shelld3v,

I remember that back in the days urlparse would behaves unexpectedly if you don't provide the scheme. That's why I force the procotol before and after.

Are you sure this PR would work correctly?

**Comment by shelld3v** [comment]
Worked really good on my side:

```python
>>> import urllib.parse
>>> urllib.parse.urlparse("google.com")
ParseResult(scheme='', netloc='', path='google.com', params='', query='', fragment='')
>>>
```

**Comment by maurosoria** [comment]
> Worked really good on my side:
> 
> ```python
> >>> import urllib.parse
> >>> urllib.parse.urlparse("google.com")
> ParseResult(scheme='', netloc='', path='google.com', params='', query='', fragment='')
> >>>
> ```

But look the ParseResult, the path should be the netloc. Probably we should use something like normalize_url

**Comment by shelld3v** [comment]
What about now?

**Pull request merged**
